export const UserStatus = {
  NEW: "NEW",
  AWAITING_PAYMENT: "AWAITING_PAYMENT",
  PAYMENT_SUBMITTED: "PAYMENT_SUBMITTED",
  VERIFIED: "VERIFIED",
  COMPLETED: "COMPLETED"
} as const;

export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus];

export const ConversationStep = {
  WELCOME: "WELCOME",
  ASK_PROCEED: "ASK_PROCEED",
  FAQ_MENU: "FAQ_MENU",
  CONFIDENTIALITY: "CONFIDENTIALITY",
  OPTIONS: "OPTIONS",
  WAITING_PAYMENT: "WAITING_PAYMENT",
  PAYMENT_ISSUE_MENU: "PAYMENT_ISSUE_MENU",
  COLLECT_FULL_NAME: "COLLECT_FULL_NAME",
  COLLECT_DOB: "COLLECT_DOB",
  COLLECT_BIRTH_TIME: "COLLECT_BIRTH_TIME",
  COLLECT_BIRTH_TIME_EXACT_VALUE: "COLLECT_BIRTH_TIME_EXACT_VALUE",
  COLLECT_BIRTH_TIME_APPROX_VALUE: "COLLECT_BIRTH_TIME_APPROX_VALUE",
  COLLECT_BIRTH_PLACE: "COLLECT_BIRTH_PLACE",
  COLLECT_CURRENT_LOCATION: "COLLECT_CURRENT_LOCATION",
  COLLECT_GENDER: "COLLECT_GENDER",
  AWAITING_VERIFICATION: "AWAITING_VERIFICATION",
  VERIFIED_NOTIFIED: "VERIFIED_NOTIFIED",
  COMPLETED: "COMPLETED"
} as const;

export type ConversationStep =
  (typeof ConversationStep)[keyof typeof ConversationStep];
